# Sample content for values-prod.yaml
local-file-organizer:
  image:
    repository: sogumai/local_file_organizer
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"