# Sample content for values-prod.yaml
json-crack:
  image:
    repository: sogumai/json_crack
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "600m"
      memory: "768Mi"