# Sample content for values-staging.yaml
json-crack:
  image:
    repository: sogumai/json_crack
    tag: staging
  replicaCount: 2
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "384Mi"