# Sample content for values-prod.yaml
anything-llm:
  image:
    repository: sogumai/anything_llm
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 3001
  resources:
    requests:
      cpu: "600m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"