# Sample content for values-dev.yaml
pake:
  image:
    repository: your-dockerhub-username/pake
    tag: dev
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8081
  resources:
    requests:
      cpu: "150m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"