# Sample content for values-staging.yaml
local-send:
  image:
    repository: sogumai/local_send
    tag: staging
  replicaCount: 2
  service:
    type: ClusterIP
    port: 5050
  resources:
    requests:
      cpu: "150m"
      memory: "128Mi"
    limits:
      cpu: "350m"
      memory: "384Mi"
