# Sample content for values-dev.yaml
local-file-organizer:
  image:
    repository: sogumai/local_file_organizer
    tag: dev
  replicaCount: 1
  service:
    type: ClusterIP
    port: 4000
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"