apiVersion: v1
kind: Service
metadata:
  name: pake
  labels:
    app: pake
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: pake
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
  labels:
    app: ocr-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ocr-service
---
apiVersion: v1
kind: Service
metadata:
  name: anything-llm
  labels:
    app: anything-llm
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: anything-llm
---
apiVersion: v1
kind: Service
metadata:
  name: json-crack
  labels:
    app: json-crack
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: json-crack
---
apiVersion: v1
kind: Service
metadata:
  name: local-send
  labels:
    app: local-send
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: http
  selector:
    app: local-send
---
apiVersion: v1
kind: Service
metadata:
  name: local-file-organizer
  labels:
    app: local-file-organizer
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: local-file-organizer
---
apiVersion: v1
kind: Service
metadata:
  name: kestra
  labels:
    app: kestra
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: kestra
---
apiVersion: v1
kind: Service
metadata:
  name: windmill
  labels:
    app: windmill
spec:
  type: ClusterIP
  ports:
    - port: 7780
      targetPort: 7780
      protocol: TCP
      name: http
  selector:
    app: windmill
---
# Kafka service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      protocol: TCP
      name: kafka
  selector:
    app: kafka
  type: ClusterIP
---
# Zookeeper service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
      name: client
    - port: 2888
      protocol: TCP
      name: follower
    - port: 3888
      protocol: TCP
      name: election
  selector:
    app: zookeeper
  type: ClusterIP
