apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sogum-ai
  name: sogum-ai-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sogum-ai-rolebinding
  namespace: sogum-ai
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sogum-ai
roleRef:
  kind: Role
  name: sogum-ai-role
  apiGroup: rbac.authorization.k8s.io
