# Sample content for values-prod.yaml
ocr-service:
  image:
    repository: your-dockerhub-username/ocr-service
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: "300m"
      memory: "256Mi"
    limits:
      cpu: "800m"
      memory: "768Mi"