# Sample content for values-staging.yaml
ocr-service:
  image:
    repository: your-dockerhub-username/ocr-service
    tag: staging
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"