{{- if .Values.openshift.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "idp.fullname" . }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.openshift.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  host: {{ .Values.openshift.host | default (printf "%s.%s" (include "idp.fullname" .) "apps.example.com") }}
  to:
    kind: Service
    name: {{ include "idp.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}
