# File: helm-idp-umbrella-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sogum-idp-secrets
  namespace: sogum-idp
type: Opaque
data:
  # Replace these with base64 encoded values or use external secret manager integration
  DB_PASSWORD: {{ .Values.global.dbPassword | b64enc | quote }}
