# Sample content for values-prod.yaml
kafka_zookeeper:
  enabled: true
  kafka:
    replicaCount: 3
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "600m"
        memory: "1Gi"
      limits:
        cpu: "1.5"
        memory: "2Gi"
  zookeeper:
    replicaCount: 3
    persistence:
      enabled: false
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
