# Sample content for values-dev.yaml
json_crack:
  image:
    repository: sogumai/json_crack
    tag: dev
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"