apiVersion: v2
name: sogum-umbrella
description: "Umbrella Helm Chart for SOGUM Intelligent Document Processing Platform"
type: application
version: 0.1.0
appVersion: "1.0"

maintainers:
  - name: John King
    email: sogumint@gmail.com

keywords:
  - sogum
  - document-processing
  - helm
  - umbrella

dependencies:
  - name: local_file_organizer
    version: 0.1.0
    repository: "file://charts/local_file_organizer"
  - name: email-router-service
    version: 0.1.0
    repository: file://../helm-base-charts/email-router-service
  - name: docetl
    version: 0.1.0
    repository: "file://charts/docetl"
    condition: docetl.enabled
  - name: anything_llm
    version: 0.1.0
    repository: "file://charts/anything-llm"
  - name: ocr-service
    version: 0.1.0
    repository: "file://charts/ocr-service"
  - name: json-crack
    version: 0.1.0
    repository: "file://charts/json-crack"
  - name: kestra-windmill
    version: 0.1.0
    repository: "file://charts/kestra-windmill"
  - name: local-send
    version: 0.1.0
    repository: "file://charts/local-send"
  - name: pake
    version: 0.1.0
    repository: "file://charts/pake"
  - name: kafka-zookeeper
    version: 0.1.0
    repository: "file://charts/kafka-zookeeper"
