apiVersion: v2
name: sogum-umbrella
description: "Umbrella Helm Chart for SOGUM Intelligent Document Processing Platform"
type: application
version: 0.1.0
appVersion: "1.0"
home: https://github.com/your-org/sogum-platform
sources:
  - https://github.com/your-org/sogum-platform
icon: https://raw.githubusercontent.com/your-org/sogum-platform/main/assets/logo.png

maintainers:
  - name: John King
    email: sogumint@gmail.com
    url: https://github.com/johnking

keywords:
  - sogum
  - document-processing
  - helm
  - umbrella
  - ai
  - llm
  - ocr
  - etl
  - microservices
  - kubernetes

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "true"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - Initial release
    - Support for multiple document processing services
    - Integrated AI/LLM capabilities
    - OCR and ETL pipeline support
  artifacthub.io/images: |
    - name: anything-llm
      image: sogumai/anything_llm:latest
    - name: docetl
      image: sogumai/docetl:latest
    - name: ocr-service
      image: sogumai/ocr_service:latest
    - name: local-file-organizer
      image: sogumai/local_file_organizer:latest
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.sogum.ai
    - name: Support
      url: https://github.com/your-org/sogum-platform/issues

dependencies:
  - name: local_file_organizer
    version: 0.1.0
    repository: "file://charts/local_file_organizer"
  - name: email-router-service
    version: 0.1.0
    repository: file://../helm-base-charts/email-router-service
  - name: docetl
    version: 0.1.0
    repository: "file://charts/docetl"
    condition: docetl.enabled
  - name: anything_llm
    version: 0.1.0
    repository: "file://charts/anything-llm"
  - name: ocr-service
    version: 0.1.0
    repository: "file://charts/ocr-service"
  - name: json-crack
    version: 0.1.0
    repository: "file://charts/json-crack"
  - name: kestra-windmill
    version: 0.1.0
    repository: "file://charts/kestra-windmill"
  - name: local-send
    version: 0.1.0
    repository: "file://charts/local-send"
  - name: pake
    version: 0.1.0
    repository: "file://charts/pake"
  - name: kafka-zookeeper
    version: 0.1.0
    repository: "file://charts/kafka-zookeeper"
