apiVersion: v2
name: intelligent-document-processing
description: An umbrella Helm chart for Intelligent Document Processing
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: service1
    version: 0.1.0
    repository: "file://charts/service1"
  - name: service2
    version: 0.1.0
    repository: "file://charts/service2"
