# Sample content for values.yaml

fullnameOverride: sogum-idp

global:
  environment: default

common:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

ocr_service:
  image:
    repository: sogumai/ocr_service
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  resources: {}

docetl:
  image:
    repository: sogumai/docetl
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

local_file_organizer:
  replicaCount: 1
  image:
    repository: sogumai/local_file_organizer
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  healthCheck:
    path: /health
    port: 4000
  config:
    SCAN_DIR: "/app/data"
    FILE_TYPES: "pdf,docx,jpg"

anything_llm:
  image:
    repository: sogumai/anything_llm
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  resources: {}

json_crack:
  image:
    repository: sogumai/json_crack
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  resources: {}

local_send:
  image:
    repository: sogumai/local_send
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5050
  resources: {}

pake:
  image:
    repository: sogumai/pake
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  resources: {}

kestra:
  image:
    repository: sogumai/kestra
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8082
  resources: {}

windmill:
  image:
    repository: sogumai/windmill
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 7780
  resources: {}

kafka_zookeeper:
  enabled: true
  kafka:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: "ocs-storagecluster-ceph-rbd"  # OKD default storage class example
      size: 10Gi
  zookeeper:
    replicaCount: 1
    persistence:
      enabled: true
      storageClass: "ocs-storagecluster-ceph-rbd"
      size: 10Gi

ingress:
  enabled: false    # disable ingress for OKD

route:
  enabled: true
  host: sogum-idp.local
  tls:
    enabled: false
    termination: edge

openshift:
  enabled: false
  host: ""  # Optional: Override host for Route
  annotations: {}  # Optional: Add annotations like cert-manager.io if needed

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

containerSecurityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

