global:
  environment: prod

common:
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

ocr_service:
  image:
    repository: sogumai/ocr_service
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 512Mi

docetl:
  image:
    repository: sogumai/docetl
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

local_file_organizer:
  replicaCount: 3
  image:
    repository: sogumai/local_file_organizer
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  healthCheck:
    path: /health
    port: 4000
  config:
    SCAN_DIR: "/app/data"
    FILE_TYPES: "pdf,docx,jpg"

anything_llm:
  image:
    repository: sogumai/anything_llm
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

json_crack:
  image:
    repository: sogumai/json_crack
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

local_send:
  image:
    repository: sogumai/local_send
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 5050
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

pake:
  image:
    repository: sogumai/pake
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 512Mi

kestra:
  image:
    repository: sogumai/kestra
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8082
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 512Mi

windmill:
  image:
    repository: sogumai/windmill
    tag: latest
  replicaCount: 3
  service:
    type: ClusterIP
    port: 7780
  resources:
    limits:
      cpu: 800m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 512Mi

kafka_zookeeper:
  enabled: true
  kafka:
    replicaCount: 3
    persistence:
      enabled: true
  zookeeper:
    replicaCount: 3
    persistence:
      enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: sogum-idp.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sogum-idp.yourdomain.com
      secretName: sogum-idp-tls
