# Sample content for values-dev.yaml
docetl:
  image:
    repository: sogumai/docetl
    tag: dev
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"