# Sample content for values-dev.yaml
anything_llm:
  image:
    repository: sogumai/anything_llm
    tag: dev
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3001
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"