name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          services=(ocr-service docetl local-file-organizer anything-llm json-crack local-send pake kestra windmill)
          for service in "${services[@]}"; do
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./services/$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          done

      - name: Set up SSH Agent
        if: env.SSH_PRIVATE_KEY != ''
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH to OKD On-Prem Server
        if: env.SSH_PRIVATE_KEY != '' && env.SSH_USER != '' && env.SSH_HOST != ''
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /opt/sogum-umbrella

            # Pull latest Helm dependencies
            helm dependency update

            # Deploy or upgrade the umbrella chart
            helm upgrade --install sogum-idp . -f values.yaml

            # Confirm deployment status with OKD CLI
            oc rollout status deployment/sogum-idp-kestra
            oc rollout status deployment/sogum-idp-windmill
          EOF
